### PR TITLE
Add a minimal template expression engine in C++17

### PR DESCRIPTION
**Pull request by wolfv**
This has been tested to compile with g++ and clang++

Times with g++ comparable to julia :)

### CODE REVIEW

**Comment by barche** [comment]
OK, so I just ran both benchmarks, and here are the outputs on my 2012 macbook air:

Julia:
```text
  16.682 ms (0 allocations: 0 bytes)
  12.761 ms (0 allocations: 0 bytes)
  10.303 ms (0 allocations: 0 bytes)
  12.385 ms (0 allocations: 0 bytes)
  14.702 ms (0 allocations: 0 bytes)
  22.009 ms (2 allocations: 22.89 MiB)
```

C++:
```text
Benchmarking a[1000x1000] + b[1000] - sin(c[])
===================================

MIN TIME: 1383092 ns
        = 1383.09 μs


Benchmarking super_custom_func
===============================

MIN TIME: 19705700 ns
        = 19705.70 μs
```

So if I interpret this correctly, that means that the `a + b - sin(c)` runs 10 times faster in C++ than in Julia!

The main downside I see with the C++ solution is that you need to create special functions that are compatible with the broadcasting by doing e.g. `UNARY_FUNC(sin);`.

**Comment by SylvainCorlay** [comment]
I am very impressed by the quality and the amount of work that went into the contributions.
 - Pythran
 - the C++ solution.
 - the NIM example.

**Comment by mratsim** [comment]
@barche, UNARY_FUNC is just a way to lift `sin` which works on float on a type made of float (`Point3D`). You only have to define it once in the library.

Using C++ concepts you could even define a "concept" `sin` that would apply to all types for which all fields are floats.

**Comment by SimonDanisch** [comment]
there is a bug in the julia solution that makes it 12x slower... i'll update soon :)

**Comment by SylvainCorlay** [comment]
Is there a blocker for including/merging the proposals as part of the repository?

**Comment by SimonDanisch** [comment]
not at all ;) i just thought i wait for a "this is complete, please merge"

**Comment by wolfv** [comment]
Ok here comes the message! :) I'm in the process of finishing my blog post so would be cool if it was merged.

**Comment by MasonProtter** [comment]
@SimonDanisch when will you merge this?

**Comment by SylvainCorlay** [comment]
> Ok here comes the message! :) I'm in the process of finishing my blog post so would be cool if it was merged.

> @SimonDanisch when will you merge this?

It appears to be ready to go @SimonDanisch

**Pull request merged**
