### PR TITLE
Baseline nim solution

### PR DESCRIPTION
**Pull request by mratsim**
Following discussion in https://github.com/SimonDanisch/julia-challenge/issues/1, I just decided to rebuild basic tensor functionality from scratch.

## Running the code

Easiest way to run the code is to use [choosenim](https://github.com/dom96/choosenim).

Once `choosenim` is installed you need to build nim devel with `choosenim devel`. Nim installation is done in a `~/.nimble`.

Then you can run the code with `nim c -r -d:release nim/nim_sol_mratsim.nim`

`-r`: tells the compiler to run the binary just after compilation
`-d:release`: compiles a release build (similar to C, no bound checking or asserts)

## Highlights

- Supports normal syntax within the broadcast, including creating procs, assigning variables.
- Supports non-contiguous, row-major and column-major ordered tensors
- Can output C, C++ or Javascript (and machine code)
- For row-major tensors, iteration is done in the most efficient memory order

## Limitations

- Unlike Julia, you have to also pass the tensors that will be used during iteration as parameters.
- Splitting work for multithreading requires a bit of gymnastic but is doable in ~60 lines at worst
- Using `Rank` as a generic integer parameter will allow GCC/LLVM to unroll all loops on the tensor metadata. It also allows the metadata to be allocated on the stack for huge perf boost. However in practice this prevents using functions like `squeeze` for which the change of dimensions is determined at runtime.

## Future

 - Adding multithreading
 - using GCC/LLVM pragma like assume_aligned and restrict to trigger more optimization
 - unrolling loops if needed

### CODE REVIEW

**Comment by mratsim** [comment]
I'm adding the benchmarking code in the following hours.

**Comment by mratsim** [comment]
I've noticed that in Julia `materialize` is done in-place in an existing buffer so I've done the same in Nim so that memory allocation is not a factor.

Also added a bench. I had some issues to use the latest and greatest [criterion.nim](https://github.com/LemonBoy/criterion.nim) so I also rebuild my own using Nim standard lib :P. If @LemonBoy wants to chime in on how to use criterion instead, I would be happy to.

Output on my Macbook Pro early 2015 (i5-5257U, Broadwell mobile dual core 2.7 turbo 3.1Ghz)

```
(shape: [1, 2, 3], strides: [6, 3, 1], offset: 0, storage: (data: @[1, 10, 5, 5, 7, 3]))
(shape: [5, 2], strides: [2, 1], offset: 0, storage: (data: @[8, 3, 7, 9, 3, 8, 5, 3, 7, 1]))

Simple assignation
(shape: [5, 2, 3], strides: [6, 3, 1], offset: 0, storage: (data: @[8, 80, 40, 15, 21, 9, 7, 70, 35, 45, 63, 27, 3, 30, 15, 40, 56, 24, 5, 50, 25, 15, 21, 9, 7, 70, 35, 5, 7, 3]))

In-place, similar to Julia impl
(shape: [5, 2, 3], strides: [6, 3, 1], offset: 0, storage: (data: @[8, 80, 40, 15, 21, 9, 7, 70, 35, 45, 63, 27, 3, 30, 15, 40, 56, 24, 5, 50, 25, 15, 21, 9, 7, 70, 35, 5, 7, 3]))

Complex multi statement with type conversion
(shape: [5, 2, 3], strides: [6, 3, 1], offset: 0, storage: (data: @[1.12727828058919, 1.297255090978019, 1.029220081237957, 0.3168265963213802, 0.7669963922853442, 0.9999999999999999, 0.8506221091780486, 1.065679324094626, 0.7156085706291233, 0.5003057878335346, 0.859191628789455, 1.072346394223034, 0.5584276483137685, 0.8508559734652587, 0.3168265963213802, 1.029220081237957, 1.243864280886628, 1.399612404734566, 1.100664502137075, 1.274196529364651, 1.0, 0.3168265963213802, 0.7669963922853442, 0.9999999999999999, 0.8506221091780486, 1.065679324094626, 0.7156085706291233, 0.8879964266455946, 1.129797339073468, 1.299291561428286]))

Variadic number of types with proc declaration inside
(shape: [3, 3], strides: [3, 1], offset: 0, storage: (data: @[0, 0, 0, 7, 4, 0, 0, 2, 0]))

###################
Benchmark
Warmup: 0.4253 s, result 369 (displayed to avoid compiler optimizing warmup away)
Collected 1000 samples
Average broadcast time: 0.0056s
Stddev  broadcast time: 0.0007s
Min     broadcast time: 0.0036s
Max     broadcast time: 0.0083s
```

**Comment by mratsim** [comment]
I changed the output to use ms like in Julia:

```
###################
Benchmark
Warmup: 0.4141 s, result 369 (displayed to avoid compiler optimizing warmup away)
Collected 1000 samples
Average broadcast time: 4.188ms
Stddev  broadcast time: 0.875ms
Min     broadcast time: 3.481ms
Max     broadcast time: 7.578ms
```

For reference the Julia solution gives the following timings
```
  14.340 ms (0 allocations: 0 bytes)
  12.937 ms (0 allocations: 0 bytes)
```

**Comment by LemonBoy** [comment]
```nim
import criterion

let cfg = newDefaultConfig()

benchmark(cfg):
  let
    a = randomTensor([1000, 1000], 1.0)
    b = randomTensor([1000], 1.0)
    c = 1.0
  var output = newTensor[2, float64](a.shape)

  proc materialize() {.measure.} =
    materialize(output, a, b, c):
      a + b - sin c
```
With your harness:
```
Benchmark
Warmup: 0.7305 s, result 369 (displayed to avoid compiler optimizing warmup away)
Collected 1000 samples
Average broadcast time: 0.0069s
Stddev  broadcast time: 0.0006s
Min     broadcast time: 0.0067s
Max     broadcast time: 0.0123s
```
With criterion.nim:
```
Benchmark: materialize()
Collected 100 samples
Warning: Found 2 mild and 4 extreme outliers in the time measurements
Warning: Found 2 mild and 4 extreme outliers in the cycles measurements
Time
  Time: 6.7081ms (6.6513ms .. 6.7865ms)
  R²:   0.9989 (0.9977 .. 0.9996)
  Mean: 6.6984ms (6.6605ms .. 6.7397ms)
  Std:  212.6871us (130.8810us .. 285.5998us)
Cycles
  Cycles: 12047280cycles (11941349cycles .. 12190677cycles)
  R²:     0.9989 (0.9976 .. 0.9996)
  Mean:   12029623cycles (11960694cycles .. 12106178cycles)
  Std:    382012cycles (233915cycles .. 514903cycles)
```
If you want more samples you just have to turn up the time budget a notch with, eg. `cfg.budget = 10.0` (the budget time is in seconds) or the minimum number of samples `cfg.minSamples = 1000`.

**Comment by oxinabox** [comment]
Nice work, this is awesome.
Definitely, bumps nim up a few places on my languages to learn list.
(It will have to fight it out with Rust :-P)

Is this just the task described in  4.1/4.2?
(I'm sorry I don't read nim well enough)

4.3 for me is where it gets really in interesting (to me at least).
I see applying it to arbitrary functions seems like it will obviously work (as in https://github.com/SimonDanisch/julia-challenge/pull/3/files#diff-7f0523acf6522d8908cac4b96d98dfa5R233)
I don't see the code for applying it to arbitrary types.
But again, I don't read nim well, so I might be missing it.
Like in the 4.3 example of applying it to Arrays of Point structs from GeometryTypes.
(No problem if you've not gotten up to it yet, either)

**Comment by SimonDanisch** [comment]
Exciting :)  14.340 ms vs 4.188ms is roughly what I see when I hoist `sin(c)` out of the loop in the julia version.
Not sure if nim actually infers that `sin` is pure, or if your implementation just does this optimization.
Anyways, we should put some time into making sure, that we benchmark the same thing ;)

**Comment by mratsim** [comment]
I'll add some examples but the code is generic and would apply to any types that defines `shape` (as a proc or field), `bc`, and `[]` bracket.

Relevant lines from https://github.com/SimonDanisch/julia-challenge/blob/1f6469852d6d25f05c2b5146d72b8c20bedc8212/nim/nim_sol_mratsim.nim#L135-L198

L135, L194, L197 are only concerned about AST. I can change the `output: var Tensor` to `output: typed` or `output: untyped`, to allow arbitrary types.

L155: I need `bc` defined for the type
L157, L177, L179: nnkBracketExpr is AST for `[]`

Don't worry about not being able to read the code, this is pretty advanced as it interpolates AST with code (the `quote do:` is for interpolation).

I have some idea of using one of Nim uncharted territory which is concepts

```Nim
type
  Broadcastable[Rank: static[int], T] = concept x, static NewRank
    x.shape is array[Rank, int]
    x[array[Rank, int]] is T
    x.bc(array[NewRank, int]) is Broadcastable[NewRank, int] # <--- I'm pretty sure this doesn't work as is but you see what I mean
```

**Comment by oxinabox** [comment]
@mratsim  
To be clear I was asking if 
It is the *elements* of the array are generic,
Not the array types (though I do appreciate that also).

In some array processing libraries,
if you put in your arrays anything other than integers or floats,
things can become dis-proportionally slow.

Even if those things are just simple structs with arthritic  overloads like the Point type @SimonDanisch  used in his example.

I am thinking that should all work good in your code,
because the `Tensor` is type parametric on its contents.
I just can't spot the example and timing code.

@SimonDanisch  does NextJournal support Nim?
It might be nicest to format this that way.
Or to just Jupyther,
which I know at least has experimental kernels.
(Or just using cell magic to write the cell to disk and execute shell commands, to compile and run it?)
Just so that code, results, and formatted comments can be interspersed

**Comment by oxinabox** [comment]
@SimonDanisch 
> Not sure if nim actually infers that sin is pure, or if your implementation just does this optimization.

I don't see code for that optimization in the implementation.
But nim compiled via first generating C code, then using GCC (right?).
GCC can surely do that optimization and hoist the `sin(c)` out.
I am kinda surprised julia 1.0 doesn't either.
I thought we were getting that kinda hoisting going.

**Comment by mratsim** [comment]
Yeah GCC/Clang would precompute sin outside of the loop. They probably even switch it to their own assembly implementation.

**Comment by SimonDanisch** [comment]
ok I will need to investigate this a bit to see, whether this is an actual compiler advantage compared to Julia, or if your implementation just allows this to happen more easily ;)

**Comment by mratsim** [comment]
Nim's `sin` comes from `math.h` from C standard lib so I suppose GCC/Clang has specific optimizations and knows that they don't have side-effects.

@oxinabox Ah yeah, I see, it works with any element type, though it would be much slower if you use types allocated on the heap like strings and each element would require to be dereferenced/unboxed before any operation. Thankfully, you have fine-grained control of memory allocation of each types in Nim.

Now there is one optimization/pessimization (?) that would be interesting to test is by adopting Numpy/Arraymancer iteration scheme, i.e. instead of looping with global coordinates and index each tensor using those, implement iterators at the tensor level and zip loop on those.

That means more loops to keep track of but no need to compute `coord --> real index` which might help the hardware prefetcher.

**Comment by oxinabox** [comment]
> ok I will need to investigate this a bit to see, whether this is an actual compiler advantage compared to Julia, or if your implementation just allows this to happen more easily ;)

There is nothing to investigate. The code isn't cheating by special casing `sin`.


There is perhaps an issue to raise on the julia repo about why GCC detects and hoists,
and we don't.
It isn't a problem with your julia code
Checkout the `@code_typed`  pf `@code_llvm` on 
```
function foo(xs,c)
    y = 0.0
    for x in xs
        y+=sin(c) + x
    end
end
```

It is invoking `sin` every loop.

**Comment by SimonDanisch** [comment]
I know ;) That's all clear, it just needs checking if this can be improved in the Julia compiler and if not why!
But seems like @vtjnash is on it (or at least moved the issue in the right way): https://github.com/JuliaLang/julia/issues/29285

**Comment by MasonProtter** [comment]
@mratsim very impressive! Awesome work.

**Comment by mratsim** [comment]
Updated with Point3.

I'm not too sure what this is for though: https://github.com/SimonDanisch/julia-challenge/blob/9ceefb3fca7e90ea8ee8dbb807b53d4a062db5c1/julia/solution.jl#L100

Timings:

Nim
```
###################
Benchmark
Warmup: 0.4145 s, result 369 (displayed to avoid compiler optimizing warmup away)

Tensors of Float64 bench
Collected 1000 samples
Average broadcast time: 4.140ms
Stddev  broadcast time: 0.736ms
Min     broadcast time: 3.517ms
Max     broadcast time: 8.866ms

Display output[[0,0]] to make sure it's not optimized away
0.1676656788327031

Tensor of 3D float32 points bench
Collected 1000 samples
Average broadcast time: 3.904ms
Stddev  broadcast time: 0.381ms
Min     broadcast time: 3.178ms
Max     broadcast time: 9.354ms

Display output[[0]] to make sure it's not optimized away
100.5281829833984
```

Julia
```
$ julia julia/solution.jl
  10.412 ms (0 allocations: 0 bytes)
  9.761 ms (0 allocations: 0 bytes)
  8.609 ms (0 allocations: 0 bytes)
  9.474 ms (0 allocations: 0 bytes)
  11.154 ms (0 allocations: 0 bytes)
  17.121 ms (2 allocations: 22.89 MiB)
```

**Comment by mratsim** [comment]
Note I also added `build/` to .gitignore so that compiled languages can put heir binaries here. It's too easy to accidentally add them to a PR.

**Comment by mratsim** [comment]
Btw you can merge this PR

**Pull request merged**
