### PR TITLE
Xtensor submission to the julia challenge

### PR DESCRIPTION
**Pull request by SylvainCorlay**
This is another C++ version making use of the [xtensor](https://github.com/QuantStack/xtensor) library. It matches the performances of the pure C++ and pythran versions.

Posting a medium story on this with @wolfv and @JohanMabille.

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
@SimonDanisch feel free to merge. I am pretty much done with the post - checking that all links are correct!

**Comment by SimonDanisch** [comment]
Cool! Are you talking about https://medium.com/@wolfv/the-julia-challenge-in-c-21272d36c002 or is there another one?

**Comment by SylvainCorlay** [comment]
It is another one!

**Comment by SylvainCorlay** [comment]
Merge?

**Comment by SylvainCorlay** [comment]
Thanks!

**Pull request merged**
